### ISSUE TITLE
last version 

### ISSUE THREAD

**Issue by entmor** [denpamusic/PyPlumIO#8] opened 2022-12-30 00:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hi,

i would like try last version pyplumIO, but i got error:

<img width="1496" alt="Zrzut ekranu 2022-12-30 o 01 07 16" src="https://user-images.githubusercontent.com/32103221/210022670-9d9a4810-e514-4cf3-91e5-66228de8905e.png">

and i test only simple code:

<img width="865" alt="Zrzut ekranu 2022-12-30 o 01 08 37" src="https://user-images.githubusercontent.com/32103221/210022723-f8176c21-0ca4-4915-b2fe-65e3097afd73.png">

so, i got device status (but i dont check) and error

### My environment is:

```markdown
- OS: Ubuntu 22.04
- Python: 3.10
```

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

USB to RS-485 adapter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment] 2022-12-30 07:14
Thanks for your feedback! Judging by the error, this is is not a latest version which is v0.2.33, but a head of main branch. Please understand, that main branch can include changes, which are unstable or outright broken.

Thermostats support is still not done. At this stage I just committed all work done prior to holidays. This is not yet tested on real device, so errors are to be expected.

**Comment by denpamusic** [comment] 2022-12-30 07:52
I'll really appreciate if you can help me to obtain frame message from real device though for testing purposes, as I'm currently away from home.

To do so, please run the following code and paste it's output (line of hex values) as the issue comment.

Thanks beforehand!

```python
import asyncio

from pyplumio import open_serial_connection
from pyplumio.devices import Device
from pyplumio.frames.requests import ThermostatParametersRequest
from pyplumio.frames.responses import ThermostatParametersResponse
from pyplumio.protocol import Protocol


async def _force_protocol_shutdown(protocol: Protocol):
    """Force protocol producer and consumers tasks into shutdown
    without breaking the connection."""
    protocol.cancel_tasks()
    await protocol.wait_until_done()
    for queue in protocol.queues:
        while not queue.empty():
            queue.get_nowait()
            queue.task_done()


async def main():
    """Open the ecoMAX connection and output controller data."""
    async with open_serial_connection(device="/dev/ttyUSB0") as connection:
        ecomax: Device = await connection.get_device("ecomax")
        await _force_protocol_shutdown(connection.protocol)
        await connection.protocol.writer.write(
            ThermostatParametersRequest(recipient=ecomax.address)
        )
        while True:
            frame = await connection.protocol.reader.read()
            if isinstance(frame, ThermostatParametersResponse):
                print(frame.message.hex())
                break


asyncio.run(main())
```

**Comment by entmor** [comment] 2022-12-30 10:48
hi, 

sure, i understand that some errors can be. But maybe for dev version make secound branch and merge to main only working code.

response:
`000025ffffff000007dc0064005e01960064005e01643c8c02003c01003c01003c0a003c090032de0064005e01d40064005e015a0032002c01ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
[]`

**Comment by entmor** [comment] 2022-12-30 11:07
hi,

i check last main commit and errors are gone (from first comment).


i know, that is not finally version but i check this function:
thermo = await ecomax.get_value("thermostats");
await thermo[0].set_value("thermostat_day_target_temp", 22)

and i got this: 
Traceback (most recent call last):
  File "/home/barti/Pulpit/pyplum/test.py", line 19, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/barti/Pulpit/pyplum/test.py", line 10, in main
    await thermo[0].set_value("thermostat_day_target_temp", 22)
  File "/home/barti/Pulpit/pyplum/pyplumio/devices/__init__.py", line 80, in set_value
    return await parameter.set(value)
  File "/home/barti/Pulpit/pyplum/pyplumio/helpers/parameter.py", line 159, in set
    raise ValueError(
ValueError: Parameter value must be between '24064' and '54273'

**Comment by denpamusic** [comment] 2022-12-30 11:47
> sure, i understand that some errors can be. But maybe for dev version make second branch and merge to main only working code.

Thank you for the message, it'll help a lot. As for dev branch I see no point in having two branches for now, as a whole project considered early beta and has a userbase of maybe 5-10 people :) Maybe later when we get to the first stable release. For now, to avoid errors it's better to stick to releases, they are at least tested with multiple devices via Home Assistant integration.

I'll really appreciate your help with debugging though, this should considerably speed up times between releases👍

For your second issue, that's where the message you provided will be very handy. Value error is raised because parameter was incorrectly parsed as having value between of 24064 and 54273 which is of course incorrect for `thermostat_day_target_temp` parameter. I'll plug the message you've provided into the test case and see what went wrong ASAP.

**Comment by denpamusic** [comment] 2022-12-30 15:58
Everything should hopefully work now. At least thermostat parameter parser is fixed and working as expected with the message that you provided.

Thanks again for all your help!

**Closed** 2023-01-03 00:29 UTC
Labels: bug

**Comment by entmor** [comment] 2023-01-03 01:04
Hi, 

Sometimes on start app i got message like: 
```
Can't process received frame: Incorrect frame checksum (1)
Can't process received frame: Incorrect frame checksum (22)
```

and when i try get regdata (or subscribe regdata), 
i got nothing. ( connection can be open next 10, 20 min or more and still regdata (subscribe) will be not available)

I must restart app (reconnect) and try again get regdata (with timeout=15), when i got regdata message, then i know, that will be ok. 

-------------------------
Thermostats fun check

```
ecomax = await connection.get_device("ecomax", timeout=10)   
thermo = await ecomax.get_value("thermostats");
print( thermo[0].data)
```
message:
`{'state': 0, 'current_temp': 21.367984771728516, 'target_temp': 21.200000762939453, 'contacts': False, 'schedule': False}`

but when i make in next steps:
```
print(await thermo[0].get_value('hysteresis'))
print( thermo[0].data)
```

i got full message:
`{'state': 0, 'current_temp': 21.367984771728516, 'target_temp': 21.200000762939453, 'contacts': False, 'schedule': False, 'mode': ThermostatParameter(device=EcoMAX, name=mode, value=0, min_value=0, max_value=7, extra=0), 'party_target_temp': ThermostatParameter(device=EcoMAX, name=party_target_temp, value=22.0, min_value=10.0, max_value=35.0, extra=0), 'summer_target_temp': ThermostatParameter(device=EcoMAX, name=summer_target_temp, value=15.0, min_value=10.0, max_value=35.0, extra=0), 'correction': ThermostatParameter(device=EcoMAX, name=correction, value=100, min_value=60, max_value=140, extra=0), 'away_timer': ThermostatParameter(device=EcoMAX, name=away_timer, value=2, min_value=0, max_value=60, extra=0), 'vent_timer': ThermostatParameter(device=EcoMAX, name=vent_timer, value=1, min_value=0, max_value=60, extra=0), 'party_timer': ThermostatParameter(device=EcoMAX, name=party_timer, value=1, min_value=0, max_value=60, extra=0), 'holiday_timer': ThermostatParameter(device=EcoMAX, name=holiday_timer, value=10, min_value=0, max_value=60, extra=0), 'hysteresis': ThermostatParameter(device=EcoMAX, name=hysteresis, value=6, min_value=0, max_value=50, extra=0), 'day_target_temp': ThermostatParameter(device=EcoMAX, name=day_target_temp, value=22.1, min_value=10.0, max_value=35.0, extra=0), 'night_target_temp': ThermostatParameter(device=EcoMAX, name=night_target_temp, value=21.2, min_value=10.0, max_value=35.0, extra=0), 'antifreeze_target_temp': ThermostatParameter(device=EcoMAX, name=antifreeze_target_temp, value=9.0, min_value=5.0, max_value=30.0, extra=0)}`

that same i got by mixer
```
mixers = await ecomax.get_value("mixers", timeout=10);
 mixer = mixers[0]
 print(mixer.data);
 ```
 
 message, but sometimes response is full
`{'current_temp': 25.925567626953125, 'target_temp': 40, 'pump': False}`


-------------------------------

next:

hysteresis on start: 0.6

thermo = await ecomax.get_value("thermostats");
print(await thermo[0].get_value('hysteresis'))
await thermo[0].set_value("hysteresis", 8)
print(await thermo[0].get_value('hysteresis'))
```
6
Timed out while trying to set 'hysteresis' parameter
8
```

every paramater on thermostats, when i try change i got "Timed out"

i try change `day_target_temp` 22.1 >> 21.5 
i got Timeout, but  `day_target_temp` changed to 47 (max 35)
i try one more time and still got Timeout but temp was 21.5

---------------------------------

thermostat hysteresis is float but here we have int, is this behavior good?

that same by mixer.insensitivity, this value in ecomax is float but here is int

**Comment by denpamusic** [comment] 2023-01-03 02:02
For first problem, that means that regdata schema response get corrupted during transmission, so PyPlumIO doesn't know what to do with regdata. For now there's no way to retry individual requests, but that is planned feature in the near future.

For second, that is expected behavior actually. Since both thermostats and mixers actually constructed from two requests. First is sub-device read-only sensor data, that is contained in `MESSAGE_SENSOR_DATA` response, and then editable parameters in `RESPONSE_MIXER_PARAMETERS` or `RESPONSE_THERMOSTAT_PARAMETERS`.

`mixers`/`thermostats` key of device.data becomes available as soon as sensors is available. By this point in time parameters might not be loaded yet. In order to ensure that both sensors and parameters are available I suggest awaiting them before getting their object like in example below.
```python
await ecomax.get_value("mixer_parameters")
mixers = ecomax.get_value("mixers")
print(mixers[0].data)
```
This way your script will wait until parameters are available and only then request sud-device collection, which will make parameters available in `Device.data`. Otherwise always just use `print(await thermo[0].get_value('hysteresis'))` like in your example. This is preferred method, since directly accessing `Device.data` is not recommended.

As for thermostats I'll look into it. This will take some more reverse-engineering i think :)

P. S. If possible, next time please create separate issues as it is hard to answer and will be hard to find in future. This time, I'll do it for you😉
